# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Question.create(title: "Web")
Question.create(title: "HTTPメソッド")
Question.create(title: "Docker")
Question.create(title: "ActiveRecord")
Question.create(title: "REST")
Question.create(title: "TCP/IP")
Question.create(title: "HTML")
Question.create(title: "アソシエーション")
Question.create(title: "form_with")
Question.create(title: "link_to")
Question.create(title: "HTTP")
Question.create(title: "API")
Question.create(title: "session")
Question.create(title: "cookie")
Question.create(title: "JSON")
Question.create(title: "N + 1問題")
Question.create(title: "GETメソッド")
Question.create(title: "HTTPS")
Question.create(title: "POSTメソッド")
Question.create(title: "HTTPリクエスト")
Question.create(title: "インスタンス")
Question.create(title: "MVC")
Question.create(title: "DELETEメソッド")
Question.create(title: "クラス")
Question.create(title: "インスタンスメソッド")
Question.create(title: "HTTPレスポンス")
Question.create(title: "StrongPatametors")
Question.create(title: "モデル")
Question.create(title: "クラスメソッド")
Question.create(title: "アセットパイプライン")
Question.create(title: "HTTPステータスコード")
Question.create(title: "デバッグ")
Question.create(title: "SSL")
Question.create(title: "秘密鍵・暗号鍵")
Question.create(title: "URL")
Question.create(title: "localhost")
Question.create(title: "resources")
Question.create(title: "JavaScript")
Question.create(title: "Webサーバ")
Question.create(title: "三層アーキテクチャ")
Question.create(title: "database.yml")
Question.create(title: "バリデーション")
Question.create(title: "環境変数")
Question.create(title: "PATHを通す")
Question.create(title: "charsetとは")
Question.create(title: "中間テーブル")



